# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-05-12 11:42:16
"""
import arcpy
from arcpy.sa import *
from sys import argv
#global variables arguments
Wayne_National_Forest_Boundary_selection_3_= arcpy.GetParameterAsText(0) #input
srtm_20_05_tif=arcpy.GetParameterAsText(1) #input
wnf_lulc_tif=arcpy.GetParameterAsText(2) #input
WNF_Streams=arcpy.GetParameterAsText(3) #input
Finalmorel=arcpy.GetParameterAsText(4) #output
def Model(Wayne_National_Forest_Boundary_selection_3_, srtm_20_05_tif, wnf_lulc_tif, WNF_Streams, Finalmorel):  # Model
    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = True
    # Check out any necessary licenses.
    arcpy.CheckOutExtension("3D")
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")
    #local variables
    wnf_lulc_proj = "H:\\pythonmapproj\\wnf_lulc_proj"
    Reclass_wnf_1 = "H:\\pythonmapproj\\Reclass_wnf_1"
    lulc_reclas = "H:\\pythonmapproj\\lulc_reclas"
    wnf_streams_shp_2_ = "H:\\pythonmapproj\\wnf_streams_shp_2_.shp"
    wnf_streams_Buffer = "H:\\pythonmapproj\\wnf_streams_Buffer"
    streams_buff = "H:\\pythonmapproj\\streams_buff"
    lulc_In_buf = "H:\\pythonmapproj\\lulc_In_buf"
    Extract_by_Mask = ""
    newrstr = "H:\\pythonmapproj\\newrstr"
    newrstrfill = "H:\\PythonMapProj\\newrstrfill"
    aspecdem = "H:\\pythonmapproj\\aspecdem"
    SSE_DEM = "H:\\pythonmapproj\\sse_dem"
    SSE_inBuff = "H:\\pythonmapproj\\SSE_inBuff"
    
    # Process: Project Raster (Project Raster) (management)
    with arcpy.EnvManager(extent="1996351.99018926 501928.465860685 2110772.05878686 611913.394558533 PROJCS[\"NAD_1983_StatePlane_Ohio_South_FIPS_3402_Feet\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic\"],PARAMETER[\"False_Easting\",1968500.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-82.5],PARAMETER[\"Standard_Parallel_1\",38.73333333333333],PARAMETER[\"Standard_Parallel_2\",40.03333333333333],PARAMETER[\"Latitude_Of_Origin\",38.0],UNIT[\"Foot_US\",0.3048006096012192]]", outputCoordinateSystem="PROJCS[\"NAD_1983_StatePlane_Ohio_South_FIPS_3402_Feet\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic\"],PARAMETER[\"False_Easting\",1968500.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-82.5],PARAMETER[\"Standard_Parallel_1\",38.73333333333333],PARAMETER[\"Standard_Parallel_2\",40.03333333333333],PARAMETER[\"Latitude_Of_Origin\",38.0],UNIT[\"Foot_US\",0.3048006096012192]]"):
        arcpy.management.ProjectRaster(in_raster=wnf_lulc_tif, out_raster=wnf_lulc_proj, out_coor_system="PROJCS[\"NAD_1983_StatePlane_Ohio_South_FIPS_3402_Feet\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic\"],PARAMETER[\"False_Easting\",1968500.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-82.5],PARAMETER[\"Standard_Parallel_1\",38.73333333333333],PARAMETER[\"Standard_Parallel_2\",40.03333333333333],PARAMETER[\"Latitude_Of_Origin\",38.0],UNIT[\"Foot_US\",0.3048006096012192]]", cell_size="30 30")
        wnf_lulc_proj = arcpy.Raster(wnf_lulc_proj)
    # Process: Reclassify (Reclassify) (sa)
    Reclassify = Reclass_wnf_1
    Reclass_wnf_1 = arcpy.sa.Reclassify(wnf_lulc_proj, "VALUE", "11 0;21 0;22 0;23 0;24 0;31 0;41 1;42 0;43 1;52 1;71 1;81 0;82 0;90 0;95 0", "DATA")
    Reclass_wnf_1.save(Reclassify)
    # Process: Clip Raster (Clip Raster) (management)
    with arcpy.EnvManager(extent="1996351.99018926 501928.465860685 2110772.05878686 611913.394558533 PROJCS[\"NAD_1983_StatePlane_Ohio_South_FIPS_3402_Feet\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic\"],PARAMETER[\"False_Easting\",1968500.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-82.5],PARAMETER[\"Standard_Parallel_1\",38.73333333333333],PARAMETER[\"Standard_Parallel_2\",40.03333333333333],PARAMETER[\"Latitude_Of_Origin\",38.0],UNIT[\"Foot_US\",0.3048006096012192]]", outputCoordinateSystem="PROJCS[\"NAD_1983_StatePlane_Ohio_South_FIPS_3402_Feet\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic\"],PARAMETER[\"False_Easting\",1968500.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-82.5],PARAMETER[\"Standard_Parallel_1\",38.73333333333333],PARAMETER[\"Standard_Parallel_2\",40.03333333333333],PARAMETER[\"Latitude_Of_Origin\",38.0],UNIT[\"Foot_US\",0.3048006096012192]]"):    
        arcpy.management.Clip(in_raster=Reclass_wnf_1, rectangle="1996351.99018926 501928.465860685 2110772.05878686 611913.394558533",out_raster=lulc_reclas, in_template_dataset=Wayne_National_Forest_Boundary_selection_3_)
        lulc_reclas = arcpy.Raster(lulc_reclas)
    # Process: Clip (Clip) (analysis)
    with arcpy.EnvManager(extent="1996351.99018926 501928.465860685 2110772.05878686 611913.394558533 PROJCS[\"NAD_1983_StatePlane_Ohio_South_FIPS_3402_Feet\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic\"],PARAMETER[\"False_Easting\",1968500.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-82.5],PARAMETER[\"Standard_Parallel_1\",38.73333333333333],PARAMETER[\"Standard_Parallel_2\",40.03333333333333],PARAMETER[\"Latitude_Of_Origin\",38.0],UNIT[\"Foot_US\",0.3048006096012192]]", outputCoordinateSystem="PROJCS[\"NAD_1983_StatePlane_Ohio_South_FIPS_3402_Feet\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic\"],PARAMETER[\"False_Easting\",1968500.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-82.5],PARAMETER[\"Standard_Parallel_1\",38.73333333333333],PARAMETER[\"Standard_Parallel_2\",40.03333333333333],PARAMETER[\"Latitude_Of_Origin\",38.0],UNIT[\"Foot_US\",0.3048006096012192]]"):
        arcpy.analysis.Clip(in_features=WNF_Streams, clip_features=Wayne_National_Forest_Boundary_selection_3_, out_feature_class=wnf_streams_shp_2_)

    # Process: Buffer (Buffer) (analysis)
    arcpy.analysis.Buffer(in_features=wnf_streams_shp_2_, out_feature_class=wnf_streams_Buffer, buffer_distance_or_field="100 Meters", method="GEODESIC")
    # Process: Feature to Raster (Feature to Raster) (conversion)
    with arcpy.EnvManager(extent="1996351.99018926 501928.465860685 2110772.05878686 611913.394558533 PROJCS[\"NAD_1983_StatePlane_Ohio_South_FIPS_3402_Feet\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic\"],PARAMETER[\"False_Easting\",1968500.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-82.5],PARAMETER[\"Standard_Parallel_1\",38.73333333333333],PARAMETER[\"Standard_Parallel_2\",40.03333333333333],PARAMETER[\"Latitude_Of_Origin\",38.0],UNIT[\"Foot_US\",0.3048006096012192]]", outputCoordinateSystem="PROJCS[\"NAD_1983_StatePlane_Ohio_South_FIPS_3402_Feet\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic\"],PARAMETER[\"False_Easting\",1968500.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-82.5],PARAMETER[\"Standard_Parallel_1\",38.73333333333333],PARAMETER[\"Standard_Parallel_2\",40.03333333333333],PARAMETER[\"Latitude_Of_Origin\",38.0],UNIT[\"Foot_US\",0.3048006096012192]]"):
        arcpy.conversion.FeatureToRaster(in_features=wnf_streams_Buffer, field="BUFF_DIST", out_raster=streams_buff)
        streams_buff = arcpy.Raster(streams_buff)
    # Process: Extract by Mask (Extract by Mask) (sa)
    with arcpy.EnvManager(extent="1996351.99018926 501928.465860685 2110772.05878686 611913.394558533 PROJCS[\"NAD_1983_StatePlane_Ohio_South_FIPS_3402_Feet\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic\"],PARAMETER[\"False_Easting\",1968500.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-82.5],PARAMETER[\"Standard_Parallel_1\",38.73333333333333],PARAMETER[\"Standard_Parallel_2\",40.03333333333333],PARAMETER[\"Latitude_Of_Origin\",38.0],UNIT[\"Foot_US\",0.3048006096012192]]", outputCoordinateSystem="PROJCS[\"NAD_1983_StatePlane_Ohio_South_FIPS_3402_Feet\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic\"],PARAMETER[\"False_Easting\",1968500.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-82.5],PARAMETER[\"Standard_Parallel_1\",38.73333333333333],PARAMETER[\"Standard_Parallel_2\",40.03333333333333],PARAMETER[\"Latitude_Of_Origin\",38.0],UNIT[\"Foot_US\",0.3048006096012192]]"):
        lulc_In_buf = arcpy.sa.ExtractByMask(lulc_reclas, streams_buff, "INSIDE", streams_buff)
        lulc_In_buf.save(Extract_by_Mask)
    # Process: Clip Raster (2) (Clip Raster) (management)
    with arcpy.EnvManager(extent="1996351.99018926 501928.465860685 2110772.05878686 611913.394558533 PROJCS[\"NAD_1983_StatePlane_Ohio_South_FIPS_3402_Feet\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic\"],PARAMETER[\"False_Easting\",1968500.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-82.5],PARAMETER[\"Standard_Parallel_1\",38.73333333333333],PARAMETER[\"Standard_Parallel_2\",40.03333333333333],PARAMETER[\"Latitude_Of_Origin\",38.0],UNIT[\"Foot_US\",0.3048006096012192]]", outputCoordinateSystem="PROJCS[\"NAD_1983_StatePlane_Ohio_South_FIPS_3402_Feet\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic\"],PARAMETER[\"False_Easting\",1968500.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-82.5],PARAMETER[\"Standard_Parallel_1\",38.73333333333333],PARAMETER[\"Standard_Parallel_2\",40.03333333333333],PARAMETER[\"Latitude_Of_Origin\",38.0],UNIT[\"Foot_US\",0.3048006096012192]]"):
        arcpy.management.Clip(in_raster=srtm_20_05_tif, rectangle="1996236.84673195 501778.762452215 2111299.47307366 612244.444172457", out_raster=newrstr, in_template_dataset=Wayne_National_Forest_Boundary_selection_3_)
        newrstr = arcpy.Raster(newrstr)
    # Process: Fill (2) (Fill) (sa)
    Fill_2_ = newrstrfill
    with arcpy.EnvManager(extent="1996351.99018926 501928.465860685 2110772.05878686 611913.394558533 PROJCS[\"NAD_1983_StatePlane_Ohio_South_FIPS_3402_Feet\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic\"],PARAMETER[\"False_Easting\",1968500.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-82.5],PARAMETER[\"Standard_Parallel_1\",38.73333333333333],PARAMETER[\"Standard_Parallel_2\",40.03333333333333],PARAMETER[\"Latitude_Of_Origin\",38.0],UNIT[\"Foot_US\",0.3048006096012192]]", outputCoordinateSystem="PROJCS[\"NAD_1983_StatePlane_Ohio_South_FIPS_3402_Feet\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic\"],PARAMETER[\"False_Easting\",1968500.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-82.5],PARAMETER[\"Standard_Parallel_1\",38.73333333333333],PARAMETER[\"Standard_Parallel_2\",40.03333333333333],PARAMETER[\"Latitude_Of_Origin\",38.0],UNIT[\"Foot_US\",0.3048006096012192]]"):
        newrstrfill = arcpy.sa.Fill(newrstr, None)
        newrstrfill.save(Fill_2_)
    # Process: Aspect (2) (Aspect) (sa)
    Aspect_2_ = aspecdem
    with arcpy.EnvManager(extent="1996351.99018926 501928.465860685 2110772.05878686 611913.394558533 PROJCS[\"NAD_1983_StatePlane_Ohio_South_FIPS_3402_Feet\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic\"],PARAMETER[\"False_Easting\",1968500.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-82.5],PARAMETER[\"Standard_Parallel_1\",38.73333333333333],PARAMETER[\"Standard_Parallel_2\",40.03333333333333],PARAMETER[\"Latitude_Of_Origin\",38.0],UNIT[\"Foot_US\",0.3048006096012192]]", outputCoordinateSystem="PROJCS[\"NAD_1983_StatePlane_Ohio_South_FIPS_3402_Feet\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic\"],PARAMETER[\"False_Easting\",1968500.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-82.5],PARAMETER[\"Standard_Parallel_1\",38.73333333333333],PARAMETER[\"Standard_Parallel_2\",40.03333333333333],PARAMETER[\"Latitude_Of_Origin\",38.0],UNIT[\"Foot_US\",0.3048006096012192]]"):
        aspecdem = arcpy.sa.Aspect(newrstrfill, "PLANAR", "METER", "GEODESIC_AZIMUTHS", "CPU_ONLY")
        aspecdem.save(Aspect_2_)
    # Process: Reclassify (2) (Reclassify) (sa)
    Reclassify_2_ = SSE_DEM
    SSE_DEM = arcpy.sa.Reclassify(aspecdem, "VALUE", "0 90 0;90 225 1;225 360 0", "DATA")
    SSE_DEM.save(Reclassify_2_)
    # Process: Extract by Mask (2) (Extract by Mask) (sa)
    Extract_by_Mask_2_ = SSE_inBuff
    with arcpy.EnvManager(extent="1996351.99018926 501928.465860685 2110772.05878686 611913.394558533 PROJCS[\"NAD_1983_StatePlane_Ohio_South_FIPS_3402_Feet\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic\"],PARAMETER[\"False_Easting\",1968500.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-82.5],PARAMETER[\"Standard_Parallel_1\",38.73333333333333],PARAMETER[\"Standard_Parallel_2\",40.03333333333333],PARAMETER[\"Latitude_Of_Origin\",38.0],UNIT[\"Foot_US\",0.3048006096012192]]", outputCoordinateSystem="PROJCS[\"NAD_1983_StatePlane_Ohio_South_FIPS_3402_Feet\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic\"],PARAMETER[\"False_Easting\",1968500.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-82.5],PARAMETER[\"Standard_Parallel_1\",38.73333333333333],PARAMETER[\"Standard_Parallel_2\",40.03333333333333],PARAMETER[\"Latitude_Of_Origin\",38.0],UNIT[\"Foot_US\",0.3048006096012192]]"):
        SSE_inBuff = arcpy.sa.ExtractByMask(SSE_DEM, streams_buff, "INSIDE", streams_buff)
        SSE_inBuff.save(Extract_by_Mask_2_)
    # Process: Weighted Sum (Weighted Sum) (sa)
    Weighted_Sum = Finalmorel
    with arcpy.EnvManager(extent="1996351.99018926 501928.465860685 2110772.05878686 611913.394558533 PROJCS[\"NAD_1983_StatePlane_Ohio_South_FIPS_3402_Feet\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic\"],PARAMETER[\"False_Easting\",1968500.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-82.5],PARAMETER[\"Standard_Parallel_1\",38.73333333333333],PARAMETER[\"Standard_Parallel_2\",40.03333333333333],PARAMETER[\"Latitude_Of_Origin\",38.0],UNIT[\"Foot_US\",0.3048006096012192]]", outputCoordinateSystem="PROJCS[\"NAD_1983_StatePlane_Ohio_South_FIPS_3402_Feet\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic\"],PARAMETER[\"False_Easting\",1968500.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-82.5],PARAMETER[\"Standard_Parallel_1\",38.73333333333333],PARAMETER[\"Standard_Parallel_2\",40.03333333333333],PARAMETER[\"Latitude_Of_Origin\",38.0],UNIT[\"Foot_US\",0.3048006096012192]]"):
        Finalmorel = arcpy.sa.WeightedSum(WSTable([[lulc_In_buf, 'VALUE', 40], [SSE_inBuff, 'VALUE', 60]]))
        Finalmorel.save(Weighted_Sum)
if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="H:\pythonmapproj", workspace="H:\pythonmapproj"):
        Model(*argv[1:])
